import React from 'react';
import { User, Mail, Phone, Calendar, Heart, Shield, Image } from 'lucide-react';

export const EmployeeBasicForm = ({ data, onChange }) => {
  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      <div className="border-b border-slate-100 pb-3">
        <h3 className="text-base font-black text-slate-900 flex items-center space-x-2">
          <User size={18} className="text-bjk-teal" />
          <span>Step 1: Employee Basic Information</span>
        </h3>
        <p className="text-xs text-slate-500 mt-0.5">
          Legal identification name, demographic details, contact coordinates, and emergency contacts.
        </p>
      </div>

      {/* Auto Employee ID & Status Banner */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-4 bg-slate-50 rounded-2xl border border-slate-200">
        <div>
          <span className="text-[10px] uppercase font-bold text-slate-400 block mb-1">Assigned Employee ID</span>
          <span className="font-mono text-sm font-black text-bjk-teal">{data.employeeId || 'BJK-EMP-AUTOGENERATED'}</span>
        </div>
        <div>
          <span className="text-[10px] uppercase font-bold text-slate-400 block mb-1">Onboarding State</span>
          <span className="text-xs font-bold text-amber-700 bg-amber-100 px-2.5 py-0.5 rounded-full inline-block">
            {data.status || 'DRAFT'}
          </span>
        </div>
        <div>
          <span className="text-[10px] uppercase font-bold text-slate-400 block mb-1">Employee Category</span>
          <select
            value={data.employeeCategory || 'Manufacturing'}
            onChange={(e) => onChange('employeeCategory', e.target.value)}
            className="w-full px-2.5 py-1 text-xs border border-slate-300 rounded-lg bg-white font-medium"
          >
            {['Management', 'Administration', 'Manufacturing', 'Quality', 'Regulatory', 'Warehouse', 'Production', 'Sales', 'Marketing', 'Finance', 'HR', 'IT', 'R&D', 'Maintenance', 'Other'].map(c => (
              <option key={c} value={c}>{c}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Name Fields */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">
            First Name <span className="text-rose-500">*</span>
          </label>
          <input
            type="text"
            required
            value={data.firstName || ''}
            onChange={(e) => onChange('firstName', e.target.value)}
            placeholder="e.g. Rajesh"
            className="w-full px-3 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-bjk-teal/20 focus:border-bjk-teal"
          />
        </div>

        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">Middle Name</label>
          <input
            type="text"
            value={data.middleName || ''}
            onChange={(e) => onChange('middleName', e.target.value)}
            placeholder="e.g. Kumar"
            className="w-full px-3 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-bjk-teal/20 focus:border-bjk-teal"
          />
        </div>

        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">
            Last Name <span className="text-rose-500">*</span>
          </label>
          <input
            type="text"
            required
            value={data.lastName || ''}
            onChange={(e) => onChange('lastName', e.target.value)}
            placeholder="e.g. Patel"
            className="w-full px-3 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-bjk-teal/20 focus:border-bjk-teal"
          />
        </div>

        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">Preferred / Display Name</label>
          <input
            type="text"
            value={data.preferredName || ''}
            onChange={(e) => onChange('preferredName', e.target.value)}
            placeholder="e.g. Rajesh Patel"
            className="w-full px-3 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-bjk-teal/20 focus:border-bjk-teal"
          />
        </div>
      </div>

      {/* Demographic Fields */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">
            Gender <span className="text-rose-500">*</span>
          </label>
          <select
            value={data.gender || 'Male'}
            onChange={(e) => onChange('gender', e.target.value)}
            className="w-full px-3 py-2 border border-slate-300 rounded-xl text-xs bg-white focus:ring-2 focus:ring-bjk-teal/20 focus:border-bjk-teal"
          >
            <option value="Male">Male</option>
            <option value="Female">Female</option>
            <option value="Other">Other</option>
            <option value="Prefer Not to Say">Prefer Not to Say</option>
          </select>
        </div>

        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">
            Date of Birth <span className="text-rose-500">*</span>
          </label>
          <input
            type="date"
            required
            value={data.dateOfBirth ? data.dateOfBirth.split('T')[0] : ''}
            onChange={(e) => onChange('dateOfBirth', e.target.value)}
            className="w-full px-3 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-bjk-teal/20 focus:border-bjk-teal"
          />
        </div>

        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">Marital Status</label>
          <select
            value={data.maritalStatus || 'Single'}
            onChange={(e) => onChange('maritalStatus', e.target.value)}
            className="w-full px-3 py-2 border border-slate-300 rounded-xl text-xs bg-white focus:ring-2 focus:ring-bjk-teal/20 focus:border-bjk-teal"
          >
            <option value="Single">Single</option>
            <option value="Married">Married</option>
            <option value="Divorced">Divorced</option>
            <option value="Widowed">Widowed</option>
          </select>
        </div>

        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">Blood Group</label>
          <select
            value={data.bloodGroup || 'O+'}
            onChange={(e) => onChange('bloodGroup', e.target.value)}
            className="w-full px-3 py-2 border border-slate-300 rounded-xl text-xs bg-white focus:ring-2 focus:ring-bjk-teal/20 focus:border-bjk-teal"
          >
            {['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map(b => (
              <option key={b} value={b}>{b}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Communication Contacts */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">Personal Email Address</label>
          <input
            type="email"
            value={data.personalEmail || ''}
            onChange={(e) => onChange('personalEmail', e.target.value)}
            placeholder="e.g. rajesh.personal@gmail.com"
            className="w-full px-3 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-bjk-teal/20 focus:border-bjk-teal"
          />
        </div>

        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">
            Primary Mobile Number <span className="text-rose-500">*</span>
          </label>
          <input
            type="tel"
            required
            value={data.phone || data.personalPhone || ''}
            onChange={(e) => { onChange('phone', e.target.value); onChange('personalPhone', e.target.value); }}
            placeholder="+91 98765 43210"
            className="w-full px-3 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-bjk-teal/20 focus:border-bjk-teal"
          />
        </div>
      </div>

      {/* Emergency Contact Group */}
      <div className="p-4 bg-slate-50 rounded-2xl border border-slate-200 space-y-3">
        <h4 className="text-xs font-bold text-slate-800 flex items-center space-x-1.5">
          <Heart size={14} className="text-rose-500" />
          <span>Emergency Contact Person</span>
        </h4>

        <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
          <div>
            <label className="block text-[11px] font-semibold text-slate-600 mb-1">Contact Name *</label>
            <input
              type="text"
              value={data.emergencyContactName || data.emergencyContact?.name || ''}
              onChange={(e) => onChange('emergencyContactName', e.target.value)}
              placeholder="e.g. Sunita Patel"
              className="w-full px-3 py-1.5 border border-slate-300 rounded-xl text-xs bg-white"
            />
          </div>

          <div>
            <label className="block text-[11px] font-semibold text-slate-600 mb-1">Relationship *</label>
            <input
              type="text"
              value={data.emergencyContactRelation || data.emergencyContact?.relation || ''}
              onChange={(e) => onChange('emergencyContactRelation', e.target.value)}
              placeholder="e.g. Spouse / Father"
              className="w-full px-3 py-1.5 border border-slate-300 rounded-xl text-xs bg-white"
            />
          </div>

          <div>
            <label className="block text-[11px] font-semibold text-slate-600 mb-1">Emergency Phone *</label>
            <input
              type="tel"
              value={data.emergencyContactPhone || data.emergencyContact?.phone || ''}
              onChange={(e) => onChange('emergencyContactPhone', e.target.value)}
              placeholder="+91 98250 12345"
              className="w-full px-3 py-1.5 border border-slate-300 rounded-xl text-xs bg-white"
            />
          </div>

          <div>
            <label className="block text-[11px] font-semibold text-slate-600 mb-1">Emergency Email</label>
            <input
              type="email"
              value={data.emergencyContactEmail || data.emergencyContact?.email || ''}
              onChange={(e) => onChange('emergencyContactEmail', e.target.value)}
              placeholder="sunita@gmail.com"
              className="w-full px-3 py-1.5 border border-slate-300 rounded-xl text-xs bg-white"
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default EmployeeBasicForm;
